{"type": "error", "data": "Error running pipeline!", "stack": "Traceback (most recent call last):\n  File \"/home/logan/GRAG/graphrag/graphrag/index/run.py\", line 309, in run_pipeline\n    workflow = workflow_to_run.workflow\n               ^^^^^^^^^^^^^^^\n  File \"/home/logan/GRAG/graphrag/graphrag/index/run.py\", line 309, in run_pipeline\n    workflow = workflow_to_run.workflow\n               ^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.11/bdb.py\", line 90, in trace_dispatch\n    return self.dispatch_line(frame)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.11/bdb.py\", line 115, in dispatch_line\n    if self.quitting: raise BdbQuit\n                      ^^^^^^^^^^^^^\nbdb.BdbQuit\n", "source": "", "details": null}
